destinationIP: 192.168.24.5
destinationPORT: 8080

# Choose one of the functions in generator.py as a sensor
function: temperature
#function: location
#function: manufacturing

# Give arguments as a list. Do not comment out "args:"
args: 
  - host20
  - block1

# Number of data going to be sent
numberOfData: 1800

# Number of sensors work at the same time
numberOfSensor: 10000

# How often the sensors are going to send data
sleepTime: 0.1
